### ISSUE TITLE
Zipkin Trace Exporter not working

### ISSUE THREAD

**Issue by thesandlord** [census-instrumentation/opencensus-node#102]
I have a very simple HTTP server and am trying to use the Zipkin Exporter.

Here is a reproduction of my code:

```javascript
const port = process.env.PORT || 3000;
const upstream_uri = process.env.UPSTREAM_URI || 'http://time.jsontest.com/';
const service_name = process.env.SERVICE_NAME || 'opencensus-test-1-v1';

const tracing = require('@opencensus/nodejs');
const propagation = require('@opencensus/propagation-b3');
const b3 = new propagation.B3Format();
const zipkin = require('@opencensus/exporter-zipkin');

const exporter = new zipkin.ZipkinTraceExporter({
  url: 'http://localhost:9411',
  serviceName: 'test',
});

tracing.start({
  propagation: b3,
  samplingRate: 1.0,
  bufferSize: 1,
  bufferTimeout: 1,
  exporter
});

const express = require('express');
const app = express();
const request = require('request-promise-native');

app.get('/', async(req, res) => {
  await request({url: upstream_uri});
  res.end(`done`);
})

app.listen(port, () => {
  console.log(`${service_name} listening on port ${port}!`);
})
```

Unfortunately, traces are never sent to Zipkin and eventually the Node process dies with:
 `socket hang up`

The same code with the default `console.log` exporter or the Jaeger exporter works fine. Not sure why Zipkin is broken. It does successfully connect to the Zipkin server in some capacity, because if I give the wrong port or url, it will immediately throw a connection error.

I tried running Zipkin both native and in Docker, neither works.

**Comment by adriancole** [comment]
@djonathascardoso can you please validate this issue? I didn't know about this repo (am not watching by default, but now am). I am literally the only fulltime staff on zipkin and working on a lot of community concerns, but this issue already cause perception damage due to @thesandlord tweeting. So if you don't have time, I'll make time

**Comment by adriancole** [comment]
The issue is that "url" wasn't a url, it was just the host/port part:

Should be 'http://localhost:9411/api/v2/spans' and that should be in the README (it is in the test)

**Comment by djonathascardoso** [comment]
Yes, it's exactly what Andrian said. Put the zipkin post url, it isn't just the server url. We'll improve the readme.
