### ISSUE TITLE
When will the latest version be submitted to NPM?

### ISSUE THREAD

**Issue by hvent90** [census-instrumentation/opencensus-node#109]
Hi all,

Thanks for providing such an amazing library.

I noticed that the Stackdriver tracing exporter on Github translates a span's attributes, but the version on NPM does not.

When will the latest version on Github be published to NPM?

I wrote a quickstart tutorial using the stackdriver tracing exporter and included the usage of attributes. I made a note that it is not currently found in the NPM module. [[PR for tutorial](https://github.com/census-instrumentation/opencensus-website/pull/288)] [[image](https://user-images.githubusercontent.com/5974764/44646007-8238a280-a98e-11e8-98b9-81aeea68d2bc.png)]

Cheers,
Henry

**Comment by prudhvireddy123** [comment]
+1, [`Node Js doc`](https://opencensus.io/guides/exporters/supported-exporters/node.js/stackdriver-stats/) . To work along with this documentation  need to publish latest code to npm

**Comment by kjin** [comment]
I batch published everything as `0.0.4` just now. Let me know if there are any additional issues!

**Comment by hvent90** [comment]
Thank you!
