### ISSUE TITLE
Package naming

### ISSUE THREAD

**Issue by ofrobots** [census-instrumentation/opencensus-node#11]
Looking into the package.json for opencensus-core, it seems the package name is: `@opencensus/opencensus-core`. Why not `@opencensus/core`? I want to make sure this is a conscious decision and the pros/cons are documented somewhere.

**Comment by kjin** [comment]
We've changed the package names to be shorter as you suggested. As for pros/cons, there aren't really any pros for keeping it as `@opencensus/opencensus-core` as far as I know. `@opencensus/core` is better because it is less redundant.

**Comment by ofrobots** [comment]
👍
