### ISSUE TITLE
@opencensus/instrumentation-grpc does not include build files

### ISSUE THREAD

**Issue by hvent90** [census-instrumentation/opencensus-node#116]
Hi all,

I am writing a tutorial on instrumenting a Node gRPC server with `@opencensus-node/instrumentation-grpc`, and unfortunately none of the application files are included in the NPM package.

![screen shot 2018-08-30 at 2 33 47 pm](https://user-images.githubusercontent.com/5974764/44880585-bb5c6580-ac61-11e8-9d0b-aa72d8580359.png)

**Comment by eduardoemery** [comment]
Thanks for noticing @hvent90 

@kjin could you check this when you update to the packages to the next version please?
