### ISSUE TITLE
Allow users to use custom metric name prefix for Stackdriver

### ISSUE THREAD

**Issue by mayurkale22** [census-instrumentation/opencensus-node#125]
Add a way to override metric name prefix. Today, OpenCensus only supports "custom.googleapis.com" (https://github.com/census-instrumentation/opencensus-node/blob/f7e053fb21528c39ca56ca214176f5de22ec95e2/packages/opencensus-exporter-stackdriver/src/stackdriver-monitoring.ts#L197), but Stackdriver supports more prefixes (https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.metricDescriptors#MetricDescriptor).

Counterpart in Java: https://github.com/census-instrumentation/opencensus-java/blob/master/exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExporterWorker.java#L250

Equivalent to census-instrumentation/opencensus-java#1057..

**Comment by songy23** [comment]
Same comment to https://github.com/census-instrumentation/opencensus-python/issues/310#issuecomment-421159257.

**Comment by isaikevych** [comment]
Done by https://github.com/census-instrumentation/opencensus-node/pull/151
