### ISSUE TITLE
TypeError: tracing.start is not a function

### ISSUE THREAD

**Issue by ubbop42** [census-instrumentation/opencensus-node#127]
Hey im getting the above error seems super weird.
`
import * as tracing from '@opencensus/nodejs';
import { StackdriverTraceExporter } from '@opencensus/exporter-stackdriver';
import * as propagation from '@opencensus/propagation-stackdriver';
//...
export const exporter = new StackdriverTraceExporter({
  projectId: GOOGLE_PROJECT_ID
});

  tracing.start({
    exporter,
    logLevel: 4,
    propagation: propagation.v1,
    // always sample traces, because sampling rate is > 1.0
    samplingRate: 1,
  });
`

**Comment by kjin** [comment]
It looks like @eduardoemery's suggestion on Gitter fixes the issue here? If I run your snippet right now I don't seem to see any errors.
