### ISSUE TITLE
Refactor [exporter-stackdriver] delay to use similar approach like in other languages

### ISSUE THREAD

**Issue by isaikevych** [census-instrumentation/opencensus-node#152]
https://github.com/census-instrumentation/opencensus-node/pull/150#issuecomment-430468167
"""One high-level comment: I think a better way may be:
For every `onRecord`, still generate `timeSeries` synchronously.
Buffer the `timeSeries` in an array and export them to backend every 1 minute (or other configured delay) asynchronously.
Export should go in parallel with `onRecord`, i.e shouldn't block each other.
This is what we did in other languages. What do you think?"""

**Comment by rueian** [comment]
Hi isaikevych,

I created the pull request #168 which makes the exporter sends metrics to Stackdriver periodically.

Could you have a look at it?

**Comment by isaikevych** [comment]
Fixed in https://github.com/census-instrumentation/opencensus-node/pull/168
