### ISSUE TITLE
[exporter-prometheus] Sanitize metric names in getPrometheusMetricName.

### ISSUE THREAD

**Issue by songy23** [census-instrumentation/opencensus-node#167]
https://github.com/census-instrumentation/opencensus-node/blob/097d1de4886e3823181ca5f2a7c11434fb4e779b/packages/opencensus-exporter-prometheus/src/prometheus-stats.ts#L158-L160.

See the original discussion on https://github.com/census-instrumentation/opencensus-node/issues/165#issuecomment-433472097.

We should replace all unsupported characters (e.g '/') with '_' for Prometheus metric names. Example in Go: https://github.com/census-instrumentation/opencensus-go/blob/master/internal/sanitize.go. Java: https://github.com/prometheus/client_java/blob/master/simpleclient/src/main/java/io/prometheus/client/Collector.java#L186-L196.

**Comment by mayurkale22** [comment]
Fixed in #217
