### ISSUE TITLE
Node package folder location assumptions are broken

### ISSUE THREAD

**Issue by dnduffy** [census-instrumentation/opencensus-node#174]
The code in package `@opencensus/exporter-ocagent` has hardcoded relative paths with the incorrect number of back references (..) when looking for `@opencensus/core/package.json`.
To get around this first problem you can run `npm install --legacy-bundling` (but you should not need to do this).

Next it will fail to find proto on ocagent.js:86 because the directory `../../../src/protos/` does not exist (nor does it exist with only two back references).  This folder exists in the repository but is not packaged into the NPM package.
The workaround for this is to copy the folder from the repo into `node_modules/@opencensus/exporter-ocagent/src/protos`

**Comment by justindsmith** [comment]
@dnduffy Thanks for the submitted issue! Sorry it took a bit of time to get around to it. I've just pushed a fix that will get picked up in the next release.
