### ISSUE TITLE
Stackdriver traces stopped appearing in 0.0.6

### ISSUE THREAD

**Issue by icco** [census-instrumentation/opencensus-node#176]
Hi there,

I can't seem to figure out what changed when reading through https://github.com/census-instrumentation/opencensus-node/compare/v0.0.4...v0.0.6, but my traces which were appearing in stackdriver with 0.0.4 stopped appearing when I upgraded to 0.0.6.

My usage of opencensus-node is roughly as follows:

```javascript

  const express = require("express");
  const logger = require("pino")({ level: "warn" });
  const opencensus = require("@opencensus/core");
  const tracing = require("@opencensus/nodejs");
  const stackdriver = require("@opencensus/exporter-stackdriver");

  const stats = new opencensus.Stats();
  const sse = new stackdriver.StackdriverStatsExporter({
    projectId: "---",
    prefix: "writing",
  });
  stats.registerExporter(sse);
  const exporter = new stackdriver.StackdriverTraceExporter({
    projectId: "---",
    prefix: "writing",
  });
  tracing.start({
    samplingRate: 1,
    plugins: {
      http: "@opencensus/instrumentation-http",
      http2: "@opencensus/instrumentation-http2",
      https: "@opencensus/instrumentation-https",
    },
    logger: logger,
    exporter: exporter,
  });
```

Any thoughts in what changed between these two versions that would stop traces from flowing the stackdriver?

**Comment by icco** [comment]
I tried simplifying the code, but that still doesn't work with 0.0.6.

```javascript
const express = require("express");
const logger = require("pino")({ level: "warn" });
const pino = require("express-pino-logger")({ logger });
const opencensus = require("@opencensus/core");
const tracing = require("@opencensus/nodejs");
const stackdriver = require("@opencensus/exporter-stackdriver");
const propagation = require("@opencensus/propagation-stackdriver");

const GOOGLE_PROJECT = "icco-cloud";

if (process.env.ENABLE_STACKDRIVER) {
  const stats = new opencensus.Stats();
  const sse = new stackdriver.StackdriverStatsExporter({
    projectId: GOOGLE_PROJECT,
  });
  stats.registerExporter(sse);

  const sp = propagation.v1;
  const ste = new stackdriver.StackdriverTraceExporter({
    projectId: GOOGLE_PROJECT,
  });
  tracing.start({
    samplingRate: 1,
    logger: logger,
    exporter: ste,
    propagation: sp,
  });
}
```

**Comment by isaikevych** [comment]
@icco Its is still in progress. Could you please use 0.0.5 or 0.0.4 at this time?

**Comment by icco** [comment]
Sure @isaikevych, is there work I can help with to get this fixed?

**Comment by isaikevych** [comment]
@icco that would be great

**Comment by isaikevych** [comment]
@icco we published new version with patch for traces.
Please let me know if it works for you.

**Comment by icco** [comment]
I tried with the code in https://github.com/census-instrumentation/opencensus-node/issues/176#issuecomment-435589192 and the traces are not showing up.

**Comment by isaikevych** [comment]
@icco could you please try example [Optional: Add a Delay](https://opencensus.io/quickstart/nodejs/tracing/)
I mixed your example and "Optional: Add a Delay" and the traces showed up.
Also, please let me know if `propagation-stackdriver`'s behavior is unexpected.

**Comment by icco** [comment]
@isaikevych how would I do that? I'm just using the default express traces. From the example you linked, it doesn't make sense.

**Comment by icco** [comment]
This is node 10, I tried open-census 0.0.7 and 0.0.5. My package.json has

```
    "@opencensus/core": "0.0.7",
    "@opencensus/exporter-stackdriver": "0.0.7",
    "@opencensus/instrumentation-all": "0.0.7",
    "@opencensus/nodejs": "0.0.7",
    "@opencensus/propagation-stackdriver": "0.0.7",
```

**Comment by isaikevych** [comment]
@icco coult you please change log level `warn` to `trace` and provide results of execution?
Your example works for me:
`{"level":20,"time":1542299598894,"msg":"starting to notify listeners the start of rootspans","pid":258888,"hostname":...,"v":1}
{"level":20,"time":1542299598895,"msg":"starting to notify listeners the end of rootspans","pid":258888,"hostname":...,"v":1}`
Also, I see results in the trace list.

I used nodejs 10, npm 6.4.1 and your package.json

**Comment by icco** [comment]
Ok, I found the bug on my side. 0.0.7 did fix the issue. Thank you @isaikevych !
