### ISSUE TITLE
exporter/Zipkin: missing fields

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-node#183]
Reported offline by @vimalraj-a
>tags and annotations are not supported in nodejs zipkin-exporter. I can help by implementing this if not someone doing it. @Authors Let me know the contribution procedure

I am filing this issue to have an actionable item but also to note that it seems like as per https://github.com/census-instrumentation/opencensus-node/blob/bf1f90c65c13861e11e6a0a137935675cae17fce/packages/opencensus-exporter-zipkin/src/zipkin.ts#L142-L152

the following are missing:
* remoteEndpoint
* status
* time events (annotations, messageEvents)
* "tags" which are from OpenCensus Attributes and Status

If this is a pain to add or needs a time investment, I think we already have the OpenCensus Agent/Service https://github.com/census-instrumentation/opencensus-service and the Agent-Node.js-Exporter which has proper Zipkin exporter translation. This is precisely one of the problems that the OpenCensus Agent/Service solves so that no need to implement exporters in every language under the sun when we could use them once :)

**Comment by mayurkale22** [comment]
@vimalraj-a Thanks for filling the issue, Please feel free to submit PR as currently no one is working on it. Contribution procedure: https://github.com/census-instrumentation/opencensus-node/blob/master/CONTRIBUTING.md
