### ISSUE TITLE
Add MetricProducer that can be registered for exporting using MetricProducerManager.

### ISSUE THREAD

**Issue by isaikevych** [census-instrumentation/opencensus-node#192]
Example [MetricProducerImpl.java](https://github.com/census-instrumentation/opencensus-java/blob/90edbd5a8a0ff10d7658bd78beae9434aee8cdbe/impl_core/src/main/java/io/opencensus/implcore/stats/MetricProducerImpl.java)

**Comment by mayurkale22** [comment]
This issue is handled by https://github.com/census-instrumentation/opencensus-node/pull/253
