### ISSUE TITLE
Stats: apply restriction on TagKey and TagValue

### ISSUE THREAD

**Issue by mayurkale22** [census-instrumentation/opencensus-node#268]
The TagKey name must meet the following requirements:

1. Must contain only printable ASCII (codes between 32 and 126 inclusive)
2. Must have length greater than zero and less than 256.
3. Must not be empty.

The TagValue name must meet the following requirements:

1. It MUST contain only printable ASCII (codes between 32 and 126)

Specs: https://github.com/census-instrumentation/opencensus-specs/blob/master/tags/TagMap.md#tagkey

**Comment by vigneshtdev** [comment]
hey i would like to help with this issue. In opencensus java it had a package called tag where different tagvalue & tagkey can be configured. Where should I look for it in this package?

**Comment by mayurkale22** [comment]
@vigneshtdev Thanks for your interest in the project, all contributions are welcomed and highly appreciated. Currently we dont have separate package for [Tags](https://github.com/census-instrumentation/opencensus-specs/tree/master/tags) api. I think we should create new one same as [Java](https://github.com/census-instrumentation/opencensus-java/tree/master/api/src/main/java/io/opencensus/tags) and [Python](https://github.com/census-instrumentation/opencensus-python/tree/master/opencensus/tags). WDYT?

**Comment by vigneshtdev** [comment]
I think that it is the correct way to go, as it will make implementation across all languages more consistent. However it would require major refactoring in both src & tst

**Comment by vigneshtdev** [comment]
Or else if such refactoring in unnecessary we can modify the existing invalidTags method. Currenlty it only check if the tagkey & tagvalue have printable characters.

**Comment by songy23** [comment]
Fixed in #280.
