### ISSUE TITLE
Add TraceParams Limits

### ISSUE THREAD

**Issue by mayurkale22** [census-instrumentation/opencensus-node#285]
Add functionality to hold global trace parameters (like Attributes, Annotations etc.). Limits will be enforced on each span in order to prevent unbounded memory increase for long-running spans.

Specs: https://github.com/census-instrumentation/opencensus-specs/blob/master/trace/TraceConfig.md#traceparams

Counterpart in Java: https://github.com/census-instrumentation/opencensus-java/blob/master/api/src/main/java/io/opencensus/trace/config/TraceParams.java

**Comment by vigneshtdev** [comment]
I can help with this one.

**Comment by mayurkale22** [comment]
@vigneshtdev Awesome, please go ahead and send the PR. 

Counterpart in Go : https://github.com/census-instrumentation/opencensus-go/pull/1015

**Comment by vigneshtdev** [comment]
Meanwhile can you look at the gist I have posted for grpc instrumentation

**Comment by mayurkale22** [comment]
> Meanwhile can you look at the gist I have posted for grpc instrumentation

Sure, I will do that today.

**Comment by vigneshtdev** [comment]
hey in case trace parameters in tracer configuration are not specified should we default to max values or mark those fields are 0?

**Comment by mayurkale22** [comment]
Closed in #311, the next part is to enforce these limits #316
