### ISSUE TITLE
UnhandledPromiseRejectionWarning ... "The metric already exists."

### ISSUE THREAD

**Issue by DazWilkin** [census-instrumentation/opencensus-node#286]
Please answer these questions before submitting a bug report.

### What version of OpenCensus are you using?

```
"@opencensus/core": "0.0.8",
"@opencensus/exporter-prometheus": "0.0.8",
"@opencensus/exporter-stackdriver": "0.0.8",
```

### What version of Node are you using?

```
node --version
v10.13.0
```

### What did you do?
If possible, provide a recipe for reproducing the error.

Wrote a simple StatsD backend for OpenCensus:
https://github.com/DazWilkin/statsd-opencensus-backend

It exports to a Stackdriver workspace and runs a Prometheus metrics exporter. By its nature, OpenCensus is a proxy to these services and is unable to query the monitoring service for existing metrics. So, rerunning my code could attempt to duplicate the creation of metrics.

I've noticed that, only (!) for some (!) Gauges, when I rerun StatsD with the backend enabled, when it encounters duplicate metrics, it balks and throws the error:

```
(node:220780) UnhandledPromiseRejectionWarning: Error: Errors during metric descriptor creation: {(metric: custom.googleapis.com/opencensus/statsd_timestamp_lag, error: The metric already exists.)}.
    at createError (statsd-opencensus-backend/node_modules/axios/lib/core/createError.js:16:15)
    at settle ([[DIR]]/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd ([statsd-opencensus-backend/node_modules/axios/lib/adapters/http.js:201:11)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:220780) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:220780) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:220780) UnhandledPromiseRejectionWarning: Error: Errors during metric descriptor creation: {(metric: custom.googleapis.com/opencensus/statsd_timestamp_lag, error: The metric already exists.)}.
    at createError (statsd-opencensus-backend/node_modules/axios/lib/core/createError.js:16:15)
    at settle ([statsd-opencensus-backend/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd ([[DIR]]/node_modules/axios/lib/adapters/http.js:201:11)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:220780) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
```
I appear unable to catch this error but, even if I were, I'd prefer to swallow it; I want metric creation to be idempotent.

### What did you expect to see?

Either: A catchable (I may be wrong) error.
Or: No error

### What did you see instead?

Curiously, I am able to duplicate the creation of:
-- all counters and timers without this issue.
-- some gauges without this isssue

So that error appears (?) inconsistent (or first occurrence).

In the above example, I receive only this one occurrence of the error, but:
```
gauges
{ georgie2: 41.518, 'statsd.timestamp_lag': 0 }
END

counters
{ 'statsd.bad_lines_seen': 0,
  'statsd.packets_received': 7,
  'statsd.metrics_received': 7,
  charlie: 3 }
END

timers
{ timmy: [ 54.7985, 2.53341, 93.1877 ] }
END
```

**Comment by mayurkale22** [comment]
Would you like to give it try with ```0.0.9``` version? I ran your example locally but couldn't see the warning or error. If you still see the issue, but share the receipe to reproduce it. Thanks.

**Comment by DazWilkin** [comment]
I'm taking some time off next week but will try to find time to try this on Monday.

**Comment by DazWilkin** [comment]
I should have frozen the list of dependency versions because I'm unable to repro this `0.0.8` today :-(

**Comment by DazWilkin** [comment]
`0.0.9` introduces a breaking change with `globalStats`

**Comment by mayurkale22** [comment]
ah I see, feel free to open this issue again. Closing for now.
