### ISSUE TITLE
Trace Exporter: Support Amazon X-Ray

### ISSUE THREAD

**Issue by BrianChristie** [census-instrumentation/opencensus-node#304]
Is it planned to add support for exporting traces to Amazon X-Ray?
There is a Golang exporter https://github.com/census-ecosystem/opencensus-go-exporter-aws 

Or is the plan to implement all new exporters in the [OpenCensus Service](https://github.com/census-instrumentation/opencensus-service) so as to avoid duplication?

Thanks!

**Comment by flands** [comment]
Recommendation would be to have the node clients send to the OC service and have the OC service send to X-ray. The best reference architecture would be node > OC agent > OC collector > destination(s)

**Comment by mayurkale22** [comment]
Closing as we agreed to use OC Service.
