### ISSUE TITLE
Binary Format serializer for TagContext

### ISSUE THREAD

**Issue by mayurkale22** [census-instrumentation/opencensus-node#326]
Add methods for serializing and deserializing ```TagContext (TagMap)``` with the binary format. The format defined in this class should be shared across all implementations of OpenCensus. It allows tags to propagate across requests. See [opencensus-specs](https://github.com/census-instrumentation/opencensus-specs/blob/master/encodings/BinaryEncoding.md#tag-context), for the specification of the cross-language binary serialization format.

Counterpart in Python: https://github.com/census-instrumentation/opencensus-python/blob/master/opencensus/tags/propagation/binary_serializer.py

Counterpart in Java: https://github.com/census-instrumentation/opencensus-java/blob/3c74cea59b7c50c65e50401305e7f7feab614a90/impl_core/src/main/java/io/opencensus/implcore/tags/propagation/SerializationUtils.java

**Comment by vigneshtdev** [comment]
I can help out with this one.

**Comment by mayurkale22** [comment]
@vigneshtdev awesome, please feel free to assign this issue to yourself and let us know if you have any questions.

**Comment by vigneshtdev** [comment]
In place of `ByteArrayDataOutput`, is using `Int8Array` or should i look to make use of `protobuf ` https://github.com/dcodeIO/ProtoBuf.js/

**Comment by mayurkale22** [comment]
It should go to ```opencensus-core -> tags -> propagation.```
