### ISSUE TITLE
B3 Propagation UX issues

### ISSUE THREAD

**Issue by kjin** [census-instrumentation/opencensus-node#340]
Working on support for propagation via OpenCensus propagation modules in Stackdriver Trace (https://github.com/googleapis/cloud-trace-nodejs/pull/950), I ran into a couple of issues:

* Because `strictNullChecks` is turned off, `B3Format` does an unsafe non-null cast ([source](https://github.com/census-instrumentation/opencensus-node/blob/38ed0a2dde9c927054c7e392ae7012b89b921577/packages/opencensus-propagation-b3/src/b3-format.ts)). The result is that consumers of this propagation library will get invalid values whenever the B3 header is not set, and crash if they depended on these values being valid (which is a reasonable assumption for TS users).
* Not a behavioral bug but there are a few superfluous falsiness checks in `B3Format` such as for `getter` and `setter`.
* The B3 propagation module exports a different interface than the Stackdriver propagation module. Stackdriver propagation exports an implementation of `Propagation`, while B3 propagation exports a class constructor. I believe they should all export the former rather than the latter.

These issues may also exist for other propagation mechanisms, I only looked at B3 in particular.

**Comment by mayurkale22** [comment]
@kjin Thanks for filling an issue. B3 and TraceContext format are using the common core propagation interface (https://github.com/census-instrumentation/opencensus-node/blob/master/packages/opencensus-core/src/trace/propagation/types.ts#L36-L40), it makes sense to implement same for the Stackdriver propagation module.

**Comment by mayurkale22** [comment]
@kjin Did you get a chance to look at this? I remember you volunteer to help with this. Let me know if you still have bandwidth to take care of this.

**Comment by kjin** [comment]
I will not have bandwidth to look at this within the next two weeks. But if it can wait I can circle back to it.
