### ISSUE TITLE
Add utils to automatically detect monitored resources.

### ISSUE THREAD

**Issue by songy23** [census-instrumentation/opencensus-node#38]
Add utils to automatically detect monitored resources based the environment that the application is running in, according to [OpenCensus MonitoredResource specs](https://github.com/census-instrumentation/opencensus-specs/blob/master/utils/MonitoredResource.md). This util should be independent of specific exporters, since it's supposed to be share between Stackdriver Stats exporter and Stackdriver Trace exporter.

Counterpart in Java: https://github.com/census-instrumentation/opencensus-java/tree/master/contrib/monitored_resource_util.

**Comment by mayurkale22** [comment]
This utils shouldn't be the part of core package.

**Comment by isaikevych** [comment]
> If possible, please avoid to keep this package in core. Also change "monitored-resource" => "resource-util" . Same work is gonna happen in Java soon : [census-instrumentation/opencensus-java#1590](https://github.com/census-instrumentation/opencensus-java/issues/1590). It is better to consider same in Node at this stage.

This new requirements blocked by [Resource API](https://github.com/census-instrumentation/opencensus-node/pull/193)

**Comment by mayurkale22** [comment]
@isaikevych We discussed yesterday, this work is not blocked by anything. Please fix the PR and include https://github.com/census-instrumentation/opencensus-node/pull/173#discussion_r234377775, also pls don't include this package in core library.

**Comment by isaikevych** [comment]
@mayurkale22 its blocked by Resources https://github.com/census-instrumentation/opencensus-java/blob/f5097ad811584ef4f5e6d8723329c4726b78432f/contrib/monitored_resource_util/src/main/java/io/opencensus/contrib/monitoredresource/util/MonitoredResourceUtils.java

List<Resource> resourceList = new ArrayList<Resource>();
resourceList.add(Resource.createFromEnvironmentVariables());
