### ISSUE TITLE
Opencensus propagation binaryformat is not on npm

### ISSUE THREAD

**Issue by jinmel** [census-instrumentation/opencensus-node#413]
npm install @opencensus/propagation-binaryformat does not exist on npm

**Comment by mayurkale22** [comment]
This (```@opencensus/propagation-binaryformat```) package is not yet published, it will be available with the next release (0.0.10). Milestone -> https://github.com/census-instrumentation/opencensus-node/milestone/2?closed=1. Will update you once it is available to use.

**Comment by vmarchaud** [comment]
@mayurkale22 Just asking for the redis plugins, we would need to publish them first before adding them to the `instrumentation-all` package, so theoretically waiting for the version `0.0.11` ? I might have misunderstood

**Comment by jinmel** [comment]
so is this getting published soon?

**Comment by mayurkale22** [comment]
I have published the package yesterday. PTAL -> https://www.npmjs.com/package/@opencensus/propagation-binaryformat. Closing the issue now.
