### ISSUE TITLE
A StackDriverStatsExporter with a metric prefix does not export stats

### ISSUE THREAD

**Issue by seanprince** [census-instrumentation/opencensus-node#434]
Please answer these questions before submitting a bug report.

### What version of OpenCensus are you using?
0.0.9

### What version of Node are you using?
10.15.1

### What did you do?
I registered a Stackdriver exporter with a metric prefix like this:
```
  const exporter = new StackdriverStatsExporter({ projectId: 'my-project-id', prefix: 'my-prefix' });
  globalStats.registerExporter(exporter);
```

### What did you expect to see?

Statistics being exported to Stackdriver.

### What did you see instead?

No data appearing in Stackdriver.

### Additional context

When I removed the prefix, like this:
```
const exporter = new StackdriverStatsExporter({ projectId: 'my-project-id' });
globalStats.registerExporter(exporter);
```
then the data starts appearing again in Stackdriver.

**Comment by mayurkale22** [comment]
Make sure to add a custom prefix with **registered  domain** ie. `prefix: 'custom.googleapis.com/my-prefix'` or `prefix: 'external.googleapis.com/my-prefix'`

```
const exporter = new StackdriverStatsExporter({ 
        projectId: 'my-project-id', 
        prefix: 'custom.googleapis.com/my-prefix'});
globalStats.registerExporter(exporter);
```

**Comment by mayurkale22** [comment]
This is introduced in 0.0.5 release -> https://github.com/census-instrumentation/opencensus-node/blob/master/CHANGELOG.md#005---2018-10-19 (**Allow users to report metrics for their registered domain (using custom prefix). This could be a breaking change if you have custom prefix without (registered) domain.**)

**Comment by mayurkale22** [comment]
Closing this issue now, please refer to my previous comment for a justification.
