### ISSUE TITLE
400 bad request when exporting traces to Stackdriver

### ISSUE THREAD

**Issue by hollandben** [census-instrumentation/opencensus-node#442]
I'm seeing the following error when sending the trace information to `https://cloudtrace.googleapis.com` using the `'@opencensus/exporter-stackdriver' package:

```json
{
  "error": {
    "code": 400,
    "message": "Invalid value at 'spans[0].time_events.time_event[0].message_event.id' (TYPE_INT64), \"78f514e909094a98804da597eb454ba7\"",
    "errors": [
      {
        "message": "Invalid value at 'spans[0].time_events.time_event[0].message_event.id' (TYPE_INT64), \"78f514e909094a98804da597eb454ba7\"",
        "domain": "global",
        "reason": "badRequest"
      }
    ],
    "status": "INVALID_ARGUMENT"
  }
}
```

From the [Google Documentation for cloud tracing](https://cloud.google.com/trace/docs/reference/v2/rest/v2/TimeEvents#messageevent), the type for the a `MessageEvent` should be a `string (int64 format)` whereas the id that is set is a hexadecimal value.

I'm not sure if the API recently made this change or something is wrong in my setup. Anyone able to confirm if this is/isn't an issue? Happy to lend a hand to fix it as well.

[Full request/response log](https://gist.github.com/hollandben/d7d75e0b99e12e110e993ea8db69500e)

**Comment by mayurkale22** [comment]
Thanks for the filling issue. I am looking into it. 

Can you please answer below questions?

- What version of OpenCensus are you using?
- What version of Node are you using?
- If possible, provide a recipe for reproducing the error

**Comment by hollandben** [comment]
Hi @mayurkale22. Thanks for the speedy response. In answer to your questions:

**What version of OpenCensus are you using?**
`0.0.9`

**What version of Node are you using?**
`10.15.3`

**If possible, provide a recipe for reproducing the error**
I'll try and get something together today/tomorrow

**Comment by hollandben** [comment]
I've created [an example repo](https://github.com/hollandben/opencensus-stackdriver-exporter-error) with steps to reproduce the error. Let me know if there's anything else you need.

**Comment by mayurkale22** [comment]
@HailongWen thanks for the detailed information. I managed to reproduce the issue, looks like this is caused because of https://github.com/census-instrumentation/opencensus-node/blob/master/packages/opencensus-instrumentation-http/src/http.ts#L413-L414. We are assigning hexadecimal value to the message id, which is not acceptable by stackdriver backend. I think we should use `number` type for id field. I will send PR to address this.

**Comment by hollandben** [comment]
Great - thanks for the quick response @mayurkale22.
