### ISSUE TITLE
Separate CLS from Tracer and make it optional

### ISSUE THREAD

**Issue by hekike** [census-instrumentation/opencensus-node#462]
**Is your feature request related to a problem? Please describe.**

Continues local storage has an overhead which maybe makes sense in applications where the developer doesn't control the instrumentation and it should happen automatically but is unnecessary in services with explicit instrumentation.

Read more about common issues with CLS in https://github.com/othiym23/node-continuation-local-storage/issues/59.

**Describe the solution you'd like**

My proposal would be to remove CLS usage from the [CoreTracer](https://github.com/census-instrumentation/opencensus-node/blob/master/packages/opencensus-core/src/trace/model/tracer.ts#L33) class and create a new class `CoreTracerCLS` which extends the `CoreTracer` and enhances it with `CLS`. Then we could expose the `CoreTracer` and keep `CoreTracerCLS` the default Tracer to avoid breaking change.

**Describe alternatives you've considered**

A bigger change would be to keep the Core OpenCensus Node module explicit and completely CLS and monkey patching free and create a new module that does the automatic instrumentation via the pure core module with CLS and require hooks.

**Additional context**

This proposal is slightly related to these changes which give more control to the developer:

- https://github.com/census-instrumentation/opencensus-node/pull/437
- https://github.com/census-instrumentation/opencensus-node/pull/441

I'm happy to help with the implementation and open a PR.

This Issue was created based on our conversation with @bogdandrutu, @mayurkale22, @kjin, @ofrobots, and @kenashcraft

**Comment by mayurkale22** [comment]
Thanks for filling the issue, feel free to shoot the PR.

**Comment by mayurkale22** [comment]
@hekike  Can we close this one via #484?

**Comment by hekike** [comment]
Yes, thank you!
