### ISSUE TITLE
Convert Opencensus Span links to Thrift Span references

### ISSUE THREAD

**Issue by jindal93** [census-instrumentation/opencensus-node#472]
The Opencensus Span links are not getting converted to Thrift Span references.

**Comment by mayurkale22** [comment]
Thanks for the filling issue. Looks like currently we just put empty list for the `references `. https://github.com/census-instrumentation/opencensus-node/blob/master/packages/opencensus-exporter-jaeger/src/jaeger-driver/index.ts#L142
