### ISSUE TITLE
Wrong translation to stackdriver span

### ISSUE THREAD

**Issue by jinmel** [census-instrumentation/opencensus-node#474]
Please answer these questions before submitting a bug report.

### What version of OpenCensus are you using?

0.0.10

### What version of Node are you using?

10.15

### What did you do?

ran examples in //examples/http/ with StackdriverTraceExporter instead of ZipkinTraceExporter

### What did you expect to see?

A span in stackdriver console

### What did you see instead?

nothing

### Additional context

it works for jaeger tracer exporter, but not with stackdriver exporter. i wonder where the bug is.

**Comment by jinmel** [comment]
I only see span for 
GET /latest/dynamic/instance-identity/document

**Comment by jinmel** [comment]
atchWriteSpans error: Invalid JSON payload received. Unknown name "uncompressed_size" at 'spans[0].time_events.time_event[0].message_event': Cannot find field.
Invalid JSON payload received. Unknown name "compressed_size" at 'spans[0].time_events.time_event[0].message_event': Cannot find field.

**Comment by jinmel** [comment]
https://github.com/googleapis/googleapis/blob/327ff9c09f4b2bcc9633f035a58ad348e45fb2a0/google/devtools/cloudtrace/v2/trace.proto#L97

**Comment by mayurkale22** [comment]
Closed in #475
