### ISSUE TITLE
Support Custom attributes in instrumentation

### ISSUE THREAD

**Issue by mhdawson** [census-instrumentation/opencensus-node#490]
**Is your feature request related to a problem? Please describe.**
We need to be able to add additional attributes beyond those which are already added when
using the automatic instrumentation (for example instrumentation-http).  More specifically
we need to be able to have access to the request/response objects so that we can extract additional information. 

I talked to @kjin and from that discussion, it sounds like that is not currently possible but that @jkin thought that it being available would make sense.  It also seems consistent with other parts of the project where you can register plugins.

**Describe the solution you'd like**
This small patch shows the experimentation I've done so far.

```js
--- a/packages/opencensus-instrumentation-http/src/http.ts
+++ b/packages/opencensus-instrumentation-http/src/http.ts
@@ -421,6 +421,10 @@ export class HttpPlugin extends BasePlugin {
           }
           span.addMessageEvent(MessageEventType.SENT, 1);

+          if (plugin.customAttributeFunction) {
+            plugin.customAttributeFunction(span.kind, span, request, response);
+          }
+
           HttpPlugin.recordStats(span.kind, tags, Date.now() - startTime);
           span.end();
         });
@@ -511,6 +515,15 @@ export class HttpPlugin extends BasePlugin {
         (options as RequestOptions).headers &&
         (options as RequestOptions).headers!.Expect);
   }
+
+  customAttributeFunction!: CustomAttributeFunction;
+  public registerCustomAttributeFunction(custFunc: CustomAttributeFunction ) {
+    this.customAttributeFunction = custFunc;
+  }
+}
+
+interface CustomAttributeFunction {
+  (kind:SpanKind, span: Span, request: ClientRequest, response: ClientResponse): void ;
 }

 const plugin = new HttpPlugin('http');
```
This is just one example, there would need to be a few places where a custom function was called in order to let attributes be added (at the very least for incoming http as well)

Currently, the client does the following which I don't think is the right answer as it depends on the singleton behavior of require, instead, the plugins in use should be available through the tracer object. 

```js
const instrument = require ('@opencensus/instrumentation-http');
instrument.plugin.registerCustomAttributeFunction((spanKind, span, request, response) => {
  console.log(request);   // in real life extract value from request or response object
  span.addAttribute('custom attribute', 'value');
});

```

**Describe alternatives you've considered**
We had looked at some of the existing events to listen on but it did not look like the request or response objects were available when those fired.  If there is already some other way to get access to the request/response objects and add attributes to spans that would be great.  In that case a pointer to the docs/places to look would be great.

**Additional context**
We are doing some initial experimentation with OpenCensus in the IBM Cloud and this is one of the things we have come across so far.

If what I've outlined makes sense I may be able to spend some cycles on building a PR but I wanted to make sure we've not missed some other way to do it and to make sure there is agreement on the general approach before getting too far along.

**Comment by vmarchaud** [comment]
I believe it could be cleaner to use the `options` of the plugin to support this use case, here is a quick example :

[opencensus-instrumentation-http/src/types.ts](https://github.com/census-instrumentation/opencensus-node/blob/master/packages/opencensus-instrumentation-http/src/types.ts#L22)
```ts

export type CustomAttributeFunction = (kind: SpanKind, span: Span, request: ClientRequest, response: ClientResponse): void;

export type HttpPluginConfig = {
  ignoreIncomingPaths?: Array<IgnoreMatcher<IncomingMessage>>;
  ignoreOutgoingUrls?: Array<IgnoreMatcher<ClientRequest>>;
  applyCustomAttributesOnSpan?: CustomAttributeFunction
};
```

And in [opencensus-instrumentation-http/src/http.ts#L423](https://github.com/census-instrumentation/opencensus-node/blob/master/packages/opencensus-instrumentation-http/src/http.ts#L423) : 
```ts
if (plugin.options.applyCustomAttributesOnSpan) {
  plugin.options.applyCustomAttributesOnSpan(span.kind, span, request, response);
}
```

Then when loading the plugin, you could pass your implementation to it : 
```ts
this.tracer = tracer.start({
 plugins: {
   'http': {
      module: '@opencensus/instrumentation-http',
      config: {
        applyCustomAttributesOnSpan: MyFunction
      }
    },
  }
})
```

What do you think ? Also we should think about the args of the method, i believe we could simplify them to only : `(span: Span, request: ClientRequest, response: ClientResponse): void;` since the span kind is already available in the span.

**Comment by mhdawson** [comment]
That sounds reasonable to me,

I think at least the response type id different between the 2 places we'd want to add attributes.  Do you think we should use a union type so that we can have a single function or have  2 functions that can be set in the options?

Based on what you think is best I can put together an initial PR.

**Comment by vmarchaud** [comment]
Not really sure on this one. Sadly @mayurkale22 is not available currently (i believe he's coming back the May 4th. Maybe @draffensperger have a take on this issue ?

I also want to mention that we may need this feature on all instrumentation package, maybe it would be easier to add it as a default options in the `BasePlugin` class ?

**Comment by mhdawson** [comment]
I agree that it would be applicable to multiple instrumentation packages although the signature would likely have to be different for each one.  I was thinking we should start with at least http and https.

**Comment by draffensperger** [comment]
I like the approach of passing in the function in the custom options for the plugin, and yes, I agree the signatures will need to differ per-plugin.

@mhdawson thanks for your willingness to take initiative on a PR. I would be happy to review it so we can get the process rolling, but we would need to wait for @mayurkale22 to get back to do the final merge.

**Comment by mhdawson** [comment]
I'm actually away starting Friday for a week anyway so I think he'll be long back by the time I get something together anyway.

If the signatures are going to be different does it still make sense to try to add it in the BasePlugin or add to each of the plugins individually?

**Comment by draffensperger** [comment]
My intuition would be to add it as an optional field to `BasePlugin` with a generic `Function` type and then had it take more specific type (with the specified args and their types) for the specific plugins.
