### ISSUE TITLE
Chore: remove node 6 ci job

### ISSUE THREAD

**Issue by mayurkale22** [census-instrumentation/opencensus-node#511]
**Node.js 6.x**, which has been maintained as a long-term stable (LTS) release line since fall of 2016, is reached its scheduled end-of-life (EOL) on April 30, 2019.

![image](https://user-images.githubusercontent.com/6525361/57477085-c46bf080-724c-11e9-86c0-17526619f40d.png)

With this, upgrade engines field to >=8.10.0.

**Comment by mayurkale22** [comment]
@draffensperger and @hekike What do you think about this?

**Comment by hekike** [comment]
Absolutely, I'm wondering if at the same time we can fine tune TypeScript builds to use more native features.  But maybe it's a less significant release in terms of ES features in V8: https://v8.dev/blog/v8-release-60

**Comment by draffensperger** [comment]
Yes, I think removing support for Node 6 makes sense given it has reached end of life.
