### ISSUE TITLE
Avoid import CLS in @opencensus/core /stats/types.ts file to make it more general. 

### ISSUE THREAD

**Issue by crdgonzalezca** [census-instrumentation/opencensus-node#527]
**Problem Description:**
In @opencensus/web-types we are trying to sync to your current @opencensus/core types files. However, we found you were importing `cls` in the stats types file. This is done in [c5a7d07c](https://github.com/census-instrumentation/opencensus-node/commit/c5a7d07c03ba32040784c3fd8b638e739be0038f#diff-3f8af03ea7f8295217dd1ec432ceda36)
 
You add this line ```import * as cls from '../internal/cls';``` and use `cls` only here ```withTagContext<T>(tags: TagMap, fn: cls.Func<T>): T;```.

As this is something internal to this project, we would like to have this more general, so we can keep on the track and copy the types.

**Solution:**
As the `cls` functionality is being used only once and it only declares a Default function type, what we propose is to declare this _default function type_ in the _stats/types.ts_ file to avoid this internal import. That is, add the next line and delete the import.

```
type Func<T> = (...args: any[]) => T;
```
Also, as this is a simple default function declaration, we think is fine to repeat this code there.

**Comment by mayurkale22** [comment]
Closed in #528
