### ISSUE TITLE
Prometheus exporter

### ISSUE THREAD

**Issue by Dragomir-Ivanov** [census-instrumentation/opencensus-node#53]
Hi guys, Is there any plan for adding Prometheus exporter, just like the `opencensus-go` does?

**Comment by kjin** [comment]
Yes, we are planning to add it within the next month.

**Comment by Dragomir-Ivanov** [comment]
That is so cool. Thanks @kjin . Feel free to close this issue.

**Comment by icco** [comment]
Excited for this! Is there any way we can help @kjin?

**Comment by kjin** [comment]
@icco It is currently still in the works. Sorry for the delay -- we had to make some changes on how the core OC Stats implementation was being added. That being said the work mostly already been done (#75) and is pending a rebase.

Thanks for your patience!

**Comment by rafaeljesus** [comment]
@kjin #75 was closed actually 😕

**Comment by kjin** [comment]
@rafaeljesus Sorry, I forgot to update this issue -- #75 was superceded with #96, which has been merged. The package has already been published and is available here: https://www.npmjs.com/package/@opencensus/exporter-prometheus

**Comment by rafaeljesus** [comment]
@kjin yeah I've found it in the code base, thank you anyway 👍
