### ISSUE TITLE
currentRootSpan != root on notifyStart

### ISSUE THREAD

**Issue by jinmel** [census-instrumentation/opencensus-node#534]
Please answer these questions before submitting a bug report.

### What version of OpenCensus are you using?

0.0.12

### What version of Node are you using?

10

### What did you do?
If possible, provide a recipe for reproducing the error.

just run examples/grpc server and client with logLevel: 'debug' on tracer

### What did you see instead?

 [debug] "2019-05-17T09:51:38.568Z"  'currentRootSpan != root on notifyStart. Need more investigation.'
[debug] "2019-05-17T09:51:38.568Z"  'starting to notify listeners the start of spans'
[debug] "2019-05-17T09:51:38.652Z"  'currentRootSpan != root on notifyEnd. Need more investigation.'
[debug] "2019-05-17T09:51:38.652Z"  'starting to notify listeners the end of spans'

### Additional context

tracer.startRootSpan<T> calls base_tracer.startRootSpan which then calls rootspan.start().

rootspan.start() calls tracer.onStartSpan() and there it checks whether currentRootSpan is equal to root span that is requested to be started. 

Is this correct for any reason? if a new root span is created, it SHOULD be different from currentRootSpan. 

This symptom happens for all instrumentation, http, grpc, mongodb and so on.

**Comment by mayurkale22** [comment]
Thanks for filling the issue. This issue has been addressed in https://github.com/census-instrumentation/opencensus-node/pull/532, PTAL.

**Comment by jinmel** [comment]
Wow that was fast. I was going to fix it myself during weekends but thanks anyway :)
