### ISSUE TITLE
Exporter/Stackdriver: Provide other way to set credential instead of ADC

### ISSUE THREAD

**Issue by yamadayuki** [census-instrumentation/opencensus-node#537]
**Is your feature request related to a problem? Please describe.**

The `@opencensus/exporter-stackdriver` requires the `GOOGLE_APPLICATION_CREDENTIALS` environment variable to send the metrics to Stackdriver using ADC. I don’t want to use `GOOGLE_APPLICATION_CREDENTIALS` environment variable to set the credentials. I’d like to set the google auth client from `google-auth-library` or pass the credential object as an option. If it is achieved, I can use the credentials encoded with Base64.

**Describe the solution you'd like**

This package requires the `auth` object to use JWT. So we can use the client using `auth.fromJSON(credentials)` if the `credentials` option is provided or the create new `GoogleAuth` instance with the `credentials` option. And then I can use `@opencensus/exporter-stackdriver` as below:

```ts
import { StackdriverTraceExporter } from "@opencensus/exporter-stackdriver";

// load the environment variable with keys encoded with Base64
const jsonContent = Buffer.from(process.env.CREDENTIALS_BASE64, "base64").toString();
const credentials = JSON.parse(jsonContent);

const exporter = StackdriverTraceExporter({
  projectId: "project-id",
  credentails: credentials,
});
```

**Describe alternatives you've considered**

I consider to inject `auth` object from `google-auth-library`. But `auth.getClient()` returns the JWT client with cache so if the developer calls `auth.getClient()` before calling `StackdriverTraceExporter.authorize` internally, this client may not include the scope `https://www.googleapis.com/auth/cloud-platform` and then the request fails.

[google-auth-library-nodejs/googleauth.ts at 37bb8c7cd0a6501103274284d9cddd6816cc881e · googleapis/google-auth-library-nodejs · GitHub](https://github.com/googleapis/google-auth-library-nodejs/blob/37bb8c7cd0a6501103274284d9cddd6816cc881e/src/auth/googleauth.ts#L692-L718)

**Additional context**

I investigated how to set the credentials in some implementation. Golang and Ruby implementations are able to inject the credentials from the JSON object.

**Golang usage**

```go
import (
	"context"
	"encoding/base64"
	"os"

	"cloud.google.com/go/trace/apiv2"
	"contrib.go.opencensus.io/exporter/stackdriver"
	"golang.org/x/oauth2/google"
	"google.golang.org/api/option"
)

func main() {
	encoded := os.Getenv("CREDENTIALS_BASE64")
	key, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return err
	}
	jwtConfig, err := google.JWTConfigFromJSON(key, trace.DefaultAuthScopes()...)
	if err != nil {
		return err
	}
	ts := jwtConfig.TokenSource(context.Background())
	clientOptions := []option.ClientOption{option.WithTokenSource(ts)}
	exporter, _ := stackdriver.NewExporter(stackdriver.Options{
		ProjectID:               "project-id",
		MonitoringClientOptions: clientOptions,
		TraceClientOptions:      clientOptions,
	})

	...
}
```

**Ruby usage**

```ruby
keyfile = Base64.strict_decode64(ENV['CREDENTIALS_BASE64'])
exporter = OpenCensus::Trace::Exporters::Stackdriver.new \
  project_id: 'project_id',
  credentials: JSON.parse(keyfile)
```

**Comment by mayurkale22** [comment]
Thanks for the request! Feel free to contribute :)

**Comment by yamadayuki** [comment]
Thanks! I'll send the PR this week 👍
