### ISSUE TITLE
HTTPS plugin results in duplicate spans

### ISSUE THREAD

**Issue by jdbennet2001** [census-instrumentation/opencensus-node#542]
### What version of OpenCensus are you using?
I have pulled the the 0.0.13 copy of OpenCensus. 

### What version of Node are you using?
Node v8.12.0 (Mac)

### What did you do?
I have written a simple Express app, and added OpenCensus

```
const express                 = require("express");
const bodyParser              = require('body-parser');
const methodOverride          = require('method-override');
const rp                      = require('request-promise');
const app                     = express();


app.use(bodyParser());
app.use(methodOverride());

app.get('/jsonplaceholder', function(req, res){
  rp('https://jsonplaceholder.typicode.com/todos/1').then(data =>{
    res.status(200).send(data);
  }, err =>{
    res.status(500).json({err: err.message});
  })
})

app.listen(3500, () => console.log("Example app listening on port 3500!"));

module.exports  = app;
```

When I invoke it, and write some code to dump the generated span data I see:
Three spans being generated. 

### What did you expect to see?

Removing the HTTPS plugin results in two spans (one incoming, one outgoing) which is correct.

```JSON
[
  {
    "spanID": "1540e59e60783bc7",
    "name": "/jsonplaceholder",
    "parentSpanId": "",
    "traceID": "2b9646a7b21d43adaa366ee2a45ca943",
    "annotations": {
      "http.user_agent": "insomnia/6.5.1",
      "status_code": "200",
      "appName": "default"
    },
    "startTime": "2019-05-21T14:00:49.548Z",
    "endTime": "2019-05-21T14:00:49.626Z",
    "duration": 78.558514
  },
  {
    "spanID": "d2341914c3d4ca96",
    "name": "GET /todos/1",
    "parentSpanId": "1540e59e60783bc7",
    "traceID": "2b9646a7b21d43adaa366ee2a45ca943",
    "annotations": {
      "status_code": "200",
      "appName": "default"
    },
    "startTime": "2019-05-21T14:00:49.564Z",
    "endTime": "2019-05-21T14:00:49.621Z",
    "duration": 57.005675
  }
]
```
### What did you see instead?
The outgoing call is registered twice:

```JSON
[
  {
    "spanID": "268bc64f314c0e37",
    "name": "/jsonplaceholder",
    "parentSpanId": "",
    "traceID": "828de57c7a444247a59868a6bc8b0745",
    "annotations": {
      "http.user_agent": "insomnia/6.5.1",
      "status_code": "200",
      "appName": "default"
    },
    "startTime": "2019-05-21T13:58:07.727Z",
    "endTime": "2019-05-21T13:58:07.877Z",
    "duration": 150.505983
  },
  {
    "spanID": "89d0e0c36415534b",
    "name": "GET /todos/1",
    "parentSpanId": "268bc64f314c0e37",
    "traceID": "828de57c7a444247a59868a6bc8b0745",
    "annotations": {
      "status_code": "200",
      "appName": "default"
    },
    "startTime": "2019-05-21T13:58:07.745Z",
    "endTime": "2019-05-21T13:58:07.872Z",
    "duration": 127.311449
  },
  {
    "spanID": "12d9fefb36b51eaa",
    "name": "GET /todos/1",
    "parentSpanId": "268bc64f314c0e37",
    "traceID": "828de57c7a444247a59868a6bc8b0745",
    "annotations": {
      "status_code": "200",
      "appName": "default"
    },
    "startTime": "2019-05-21T13:58:07.746Z",
    "endTime": "2019-05-21T13:58:07.872Z",
    "duration": 126.560446
  }
]
```

**Comment by mayurkale22** [comment]
@jdbennet2001 Thanks for reporting the issue! I am looking into it.

**Comment by mayurkale22** [comment]
Earlier we used to notify only the end of `RootSpan` to the exporter (using `listener.onEndSpan`) and exporter was responsible for transforming `RootSpan` and all its descendants/children to the respective format. But after the consolidation of Span and RootSpan, every span end gets notified to the exporter. 

Consider below scenario:
```
RootSpan {id: aaa, traceId: 12334}
   Span {id: bbb, traceId: 12334}
```
Exporters will report: 
1. RootSpan {id: aaa} and its children Span {id: bbb}
2. Span {id: bbb}

IMO, no need to iterate on `RootSpan` inside exporter to get the children. I tried same in Zipkin exporter and it worked as expected.
- [Zipkin Exporter](https://github.com/census-instrumentation/opencensus-node/blob/master/packages/opencensus-exporter-zipkin/src/zipkin.ts#L144-L147)
- [Stackdriver Exporter](https://github.com/census-instrumentation/opencensus-node/blob/master/packages/opencensus-exporter-stackdriver/src/stackdriver-cloudtrace.ts#L81-L84)
- [Jaeger Exporter](https://github.com/census-instrumentation/opencensus-node/blob/master/packages/opencensus-exporter-jaeger/src/jaeger.ts#L115-L124)

@hekike This is related to #441. WDYT?

**Comment by mayurkale22** [comment]
OR We should add existing check in zipkin exporter?
```
// Add spans of a trace together when root is ended, skip non root spans.
// adaptRootSpan() will extract child spans from root.
if (span.constructor.name !== 'RootSpan') {
      return;
}
```

**Comment by hekike** [comment]
I think we should notify all the exporters about all the spans and leave it to exporters which one to handle and when to push to buffer. 

I think the scenarios today pretty much boil down to the following options:

1. Exporter puts all the spans to the buffer when they receive (record all spans immediately)
2. Exporter waits for root span and skips on all the child spans. When root received it walks `rootSpan`.spans to consolidate spans and pushed them to the buffer. So basically record traces only when rootSpan ends.

(If I understood correctly, @bogdandrutu's opinion was that exporters don't need to wait for root span end and it's safe to put all the spans to the buffer immediately and let backend deal with it)

It's not clear for me which exporter causes the problem in this issue. 
In https://github.com/census-instrumentation/opencensus-node/pull/441 I tried to keep original behavior and added the child span "skip logic" to exporters with already existing consolidation.

**Comment by jdbennet2001** [comment]
Is the above discussion about the issue or over all architectural direction?

I am fine with writing an exporter that handles child spans (I'm working on one for MQ), it just seems strange that two entirely different spans are generated for HTTPS requests. Am I missing something?

**Comment by hekike** [comment]
@jdbennet2001 maybe I'm missing some context here. Do you see in the HTTP instrumentation plugin internals that it created two spans or do you see them in your exporter reported twice or on your backend duplicated? If it's the exporter/backend, which one do you use?

**Comment by jdbennet2001** [comment]
It's a little tricky to see. The example code is:

```
app.get('/jsonplaceholder', function(req, res){
  rp('https://jsonplaceholder.typicode.com/todos/1').then(data =>{
    res.status(200).send(data);
  }, err =>{
    res.status(500).json({err: err.message});
  })
})
```

Just two calls. But the instrumentation generates two _different_ spans for the /todos/1 call:

![image](https://user-images.githubusercontent.com/4204536/58190496-a198fd80-7c8a-11e9-8f9d-9ea087e542f7.png)
 
That seems wrong, or am I missing something?

**Comment by mayurkale22** [comment]
I think I found the root cause, as @hekike mentioned, we notify all the spans to exporters and it decides which one to handle. In **Jaeger** and **OCAgent** exporter we are skipping non root spans and allow the internal method to extract child spans from root. While in **Zipkin**, **Stackdriver** and **Console** exporters, we have both the logic in place. i.e. Writing all the spans on buffer and extracting child spans from root. This causes duplicate child spans. 

There are two approaches to handle this problem,

- Skip non root spans writing to buffer 
  - straightforward
  - same as Jaeger and OCAgent
- Remove the logic of extracting child spans from the root.
  - There might be the cases where the parent ends before the child.
  - This might break something, require more time for testing.
  - I prefer to do this in OpenTelemetry.

**Comment by hekike** [comment]
@mayurkale22 oops, my bad. I thought I sorted out to have only one of the twos.
I'm fine either way. I'm not sure this whole root only logic worth the complexity but I agree let's fix it simple now and improve it in OpenTelemetry.

**Comment by mayurkale22** [comment]
I managed to repro-d the problem and the see duplicate child spans in trace output. But unlike @jdbennet2001 I could see the two child spans with same id (spanId). I am almost done with the fix, will open PR soon.

Zipkin traces with two same duplicate child spans (**"id": "6f9cf4ae14051b39"**).
```
[
  {
    "traceId": "9313f3a0c1ad4eca8659abad114a2f99",
    "parentId": "c807e252df39c7d1",
    "id": "6f9cf4ae14051b39",
    "kind": "CLIENT",
    "name": "get /todos/1",
    "timestamp": 1558550964314000,
    "duration": 39353,
    "localEndpoint": {...},
    "annotations": [...],
    "tags": {...},
    "debug": true
  },
  {
    "traceId": "9313f3a0c1ad4eca8659abad114a2f99",
    "parentId": "c807e252df39c7d1",
    "id": "6f9cf4ae14051b39",
    "kind": "CLIENT",
    "name": "get /todos/1",
    "timestamp": 1558550964314000,
    "duration": 39353,
        "localEndpoint": {...},
    "annotations": [...],
    "tags": {...},
    "debug": true
  },
  {
    "traceId": "9313f3a0c1ad4eca8659abad114a2f99",
    "id": "c807e252df39c7d1",
    "kind": "SERVER",
    "name": "/jsonplaceholder",
    "timestamp": 1558550964293000,
    "duration": 64133,
       "localEndpoint": {...},
    "annotations": [...],
    "tags": {...},
    "debug": true,
    "shared": true
  }
]
```

Stackdriver traces with two same duplicate child spans (**"spanId": "5dcbcdf118059fff"**).
```
[
  {
    "name": "projects/../traces/b1a5ce4f32c74015a9180e29310f1f45/spans/5dcbcdf118059fff",
    "spanId": "5dcbcdf118059fff",
    "displayName": {
      "value": "GET /todos/1"
    },
    "startTime": "2019-05-22T19:01:09.529Z",
    "endTime": "2019-05-22T19:01:09.644Z",
    "attributes": {...},
    "timeEvents": {...},
    "links": {...},
    "status": {..},
    "sameProcessAsParentSpan": true,
    "childSpanCount": 0,
    "parentSpanId": "a5a2db6c3abd3685"
  },
  {
    "name": "projects/../traces/b1a5ce4f32c74015a9180e29310f1f45/spans/a5a2db6c3abd3685",
    "spanId": "a5a2db6c3abd3685",
    "displayName": {
      "value": "/jsonplaceholder"
    },
    "startTime": "2019-05-22T19:01:09.511Z",
    "endTime": "2019-05-22T19:01:09.648Z",
        "attributes": {...},
    "timeEvents": {...},
    "links": {...},
    "status": {..},
    "sameProcessAsParentSpan": true,
    "childSpanCount": 1
  },
  {
    "name": "projects/.../traces/b1a5ce4f32c74015a9180e29310f1f45/spans/5dcbcdf118059fff",
    "spanId": "5dcbcdf118059fff",
    "displayName": {
      "value": "GET /todos/1"
    },
    "startTime": "2019-05-22T19:01:09.529Z",
    "endTime": "2019-05-22T19:01:09.644Z",
        "attributes": {...},
    "timeEvents": {...},
    "links": {...},
    "status": {..},
    "sameProcessAsParentSpan": true,
    "childSpanCount": 0,
    "parentSpanId": "a5a2db6c3abd3685"
  }
]
```
