### ISSUE TITLE
span.kind set to SERVER for custom span

### ISSUE THREAD

**Issue by jdbennet2001** [census-instrumentation/opencensus-node#548]
Please answer these questions before submitting a bug report.

### What version of OpenCensus are you using?
0.0.13

### What version of Node are you using?
8.1.2

### What did you do?
If possible, provide a recipe for reproducing the error.
Generate a custom span using: 
```
  let span     = tracer.startChildSpan({name}, 0);
```

the exported the data to Zipkin.

### What did you expect to see?
The span's kind field was set to 'SERVER' instead of 'OTHER'

### Additional context

The classification code is on this line:

https://github.com/census-instrumentation/opencensus-node/blob/master/packages/opencensus-exporter-zipkin/src/zipkin.ts#L164

**Comment by mayurkale22** [comment]
AFAIK, Zipkin's span kind accepts either `CLIENT|SERVER|PRODUCER|CONSUMER` string value. I am not sure about the behavior when we pass empty string or 'OTHER' value. Any idea?

**Comment by mayurkale22** [comment]
@jdbennet2001 any idea?

**Comment by jdbennet2001** [comment]
I honestly don't have a good answer for this one.

**Comment by mayurkale22** [comment]
> I honestly don't have a good answer for this one.

Ok, np. I will check with other language folks and update this thread.

**Comment by mayurkale22** [comment]
As per my testing, anything other than `CLIENT|SERVER|PRODUCER|CONSUMER` is not acceptable by the zipkin api. 

1. With `"kind": "OTHER"`, I saw "_Cannot decode spans_" error (HTTP/1.1 400 Bad Request).
2. When I skip the `kind` field from input payload, looks like zipkin api ignores the request.

curl command:
```
curl -X POST "http://localhost:9411/api/v2/spans" 
-H "accept: application/json" -H "content-type: application/json" 
-d @data.json -vvv
```

data.json:
```
[{"traceId":"a8aba8610ed54d669807ec3859d398bb","name":"/ping","id":"c2233f96a7f843aa","kind":"OTHER","timestamp":1558648731468000,"duration":6878,"debug":true,"shared":true,"localEndpoint":{"serviceName":"test"},"tags":{"http.host":"localhost","http.method":"GET","http.path":"/ping","http.route":"/ping","http.user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36","http.status_code":"304","census.status_code":"0"},"annotations":[{"timestamp":1558648731475000,"value":"RECEIVED"}]}]
```

**Comment by mayurkale22** [comment]
@jdbennet2001 Did you get a chance to see my above comment?

**Comment by jdbennet2001** [comment]
I'm sorry, I didn't realize you were asking for feedback. I read the comment as "This is a limitation of the design, and entirely reasonable" which I'm good with. I'll close the issue.
