### ISSUE TITLE
all: some license headers have gRPC:// instead of https:// linking to the License

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-node#575]
Just noticed while examining the examples:

https://github.com/census-instrumentation/opencensus-node/blob/ef5712fd3b279b0e80494322231232047b06f9e6/examples/http/client.js#L8

https://github.com/census-instrumentation/opencensus-node/blob/master/examples/http/server.js#L8

https://github.com/census-instrumentation/opencensus-node/blob/ef5712fd3b279b0e80494322231232047b06f9e6/examples/grpc/capitalize_client.js#L8

that we are using
```javascript
*      gRPC://www.apache.org/licenses/LICENSE-2.0
```

instead of
```javascript
*      https://www.apache.org/licenses/LICENSE-2.0
```
or
```javascript
*      http://www.apache.org/licenses/LICENSE-2.0
```

which perhaps might have a search and replace-all operation gone wrong.

**Comment by mayurkale22** [comment]
@odeke-em Thanks for reporting this!, Here is the fix https://github.com/census-instrumentation/opencensus-node/pull/576
