### ISSUE TITLE
Support automatic instrumentation for MySQL

### ISSUE THREAD

**Issue by naseemkullah** [census-instrumentation/opencensus-node#584]
Please see title, thanks!

**Comment by mayurkale22** [comment]
Hi @naseemkullah! We are in the process of converging this code-base with the [OpenTelemetry project](https://github.com/open-telemetry/opentelemetry-js). Feel free to open issue there, also if you are feeling motivated, maybe you can attempt to write solution and open a PR.

**Comment by mayurkale22** [comment]
I'm going to close this issue. Feel free to reopen if you have other opinion.

**Comment by naseemkullah** [comment]
Looking forward to OpenTelemetry!
