### ISSUE TITLE
Autotracer HTTP: ignore health checks

### ISSUE THREAD

**Issue by naseemkullah** [census-instrumentation/opencensus-node#610]
**NB:** Before opening a feature request against this repo, consider whether the feature should/could be implemented in other the OpenCensus libraries in other languages. If so, please [open an issue on opencensus-specs](https://github.com/census-instrumentation/opencensus-specs/issues/new) first.

**Is your feature request related to a problem? Please describe.**
I am using the autotracer and its great, but the fact that "trace instance needs to be initialized first, if you want to enable automatic tracing for built-in plugins (HTTP in this case)" mixed with the fact that it traces every request. Does not allow me to ignore traces on `/healthz` or `/ping` or whatever the healthcheck endpoing may be. 

This is flooding the tracing backend with traces that i am not interested in.

**Describe the solution you'd like**

I want a way to ignore traces to `/healthz` or any healthcheck endpoint.

**Describe alternatives you've considered**

Explicit tracing... but too much work and might not be adopted org-wide.
Collecting health check traces... but would rather not

**Additional context**

**Comment by naseemkullah** [comment]
According to https://github.com/census-instrumentation/opencensus-specs/blob/33674c81be4996b19d31f22b7529e724dbae2113/trace/HTTP.md#sampling if I were to "Pass a specific Sampler as an option to the HTTP plugin" that would allow "Filtering out certain paths (e.g. health endpoints) to disable tracing"

Is this possible with the autotracer??

**Comment by pfyod** [comment]
You can configure tracing plugins to ignore certain paths. E.g.
```
tracing.start({
    //... rest of the configuration
    plugins: {
        http: {
            module: "@opencensus/instrumentation-http",
            config: {
                ignoreIncomingPaths: [
                    /^\/healthz/,
                ],
            },
        },
    },
});
```

**Comment by naseemkullah** [comment]
THANK YOU @pfyod !
