### ISSUE TITLE
npm error at exporter-zpages

### ISSUE THREAD

**Issue by danielkhan** [census-instrumentation/opencensus-node#62]
On a fresh clone, running npm install exits with an error
```
lerna ERR! execute Error occured with '@opencensus/exporter-zpages' while running 'npm run prepare'
{ Error: Command failed: npm run prepare
npm ERR! missing script: compile;
...}
```

**Comment by kjin** [comment]
Are you running on Windows? It looks like the [compile script is bash-specific](https://github.com/census-instrumentation/opencensus-node/blob/db46f4ff51042df501b1c625d61714bf8799c833/packages/opencensus-exporter-zpages/package.json#L14).
@djonathascardoso would you mind looking into this?

**Comment by djonathascardoso** [comment]
Probably is a problem with Windows. @danielkhan could you confirm your OS?

**Comment by kjin** [comment]
@djonathascardoso I was able to re-produce this on Windows. We should rethink the process for having multiple commands in a single script, since `;` is not portable (also, it ignores exit values).

**Comment by OsvaldoRosado** [comment]
I ran into this as well. Definitely Windows specific. Quick and easy workaround is to use WSL/Bash on Windows https://docs.microsoft.com/en-us/windows/wsl/install-win10

`;` vs `&&` isn't the only problem. There's also reliance on POSIX tools like `cp`

**Comment by danielkhan** [comment]
Yes I can confirm that this happened on a windows machine. Thank you for the swift response.

**Comment by kjin** [comment]
@OsvaldoRosado @danielkhan Thanks for the responses. Supporting Windows is important (after all, we don't want to be restrictive on the platform) but at this early stage we haven't had a chance to fully test things about on Windows.

I will go through the npm scripts and make changes that will be more cross-platform, but I think some more complex commands might need to warrant a longer-term solution.
