### ISSUE TITLE
Conform to Google's TypeScript Style Guide

### ISSUE THREAD

**Issue by kjin** [census-instrumentation/opencensus-node#8]
The current [`tsconfig.json`](https://github.com/census-instrumentation/opencensus-node/blob/cbce1427643c05f6a4c9ec4e6cb5bc5eaf16b4e0/packages/opencensus-core/tsconfig.json) seems to disable important compiler checks. They should be enabled as per Google's guidelines on TypeScript style.

**Comment by fabiogomessilva** [comment]
Was addressed by #35
