### ISSUE TITLE
Please update gcp-metadata dependency to >= 4.1.0

### ISSUE THREAD

**Issue by lovrop** [census-instrumentation/opencensus-node#808]
### What version of OpenCensus are you using?

0.0.20

### What version of Node are you using?

13.12 (immaterial as far as I know)

### What did you do?

Ran a Node server while connected to the Internet via an ISP which rewrites queries to the nonexistent `metadata.google.internal` host. 

### What did you expect to see?

Server starts up.

### What did you see instead?

Uncatchable error emanating from `gcp-metadata` due to a combination of the inability to talk to Google's internal metadata service and the ISP mangling the query. This issue is especially hard to deal with here because of how early the Opencensus Node library is imported and initialised (by design).

### Additional context

This is a long-standing issue which quite a few of my colleagues have hit when working from home. The issue is described in detail at https://github.com/googleapis/gcp-metadata/issues/331. The folks there were kind enough to adjust the behaviour of the library. 

Can you please update this library to pull in a new enough version of `gcp-metadata` (>=4.1.0)? Thank you! I notice there is already #784 but some tests fail.

**Comment by aabmass** [comment]
Thanks for reporting this. One problem here is gcp-metadata v4 has dropped node8 support. We may decide to drop node8 support here as well (which we might do).

**Comment by aabmass** [comment]
There is also a security vulnerability:

```bash
~/repo/opencensus-node/packages/opencensus-resource-util (audit)$ npm audit --production
# npm audit report

json-bigint  <1.0.0
Severity: high
Uncontrolled Resource Consumption in json-bigint - https://npmjs.com/advisories/1690
fix available via `npm audit fix --force`
Will install gcp-metadata@4.3.0, which is a breaking change
node_modules/json-bigint
  gcp-metadata  0.8.0 - 4.1.0
  Depends on vulnerable versions of json-bigint
  node_modules/gcp-metadata

2 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force
```
