### ISSUE TITLE
CoreTracerBase not respecting propagation options properly

### ISSUE THREAD

**Issue by philicious** [census-instrumentation/opencensus-node#810]
### What version of OpenCensus are you using?
0.0.20 (but affects latest) 

### What version of Node are you using?
10/dubnium

### What did you do?
send a propagation header with DO-NOT-SAMPLE flag set, 
e.g. with using `@opencensus/exporter-jaeger` you would send `uber-trace-id: :::0` where 0 means do-not-sample.

### What did you expect to see?
sample decision would be false

### What did you see instead?
sample decision is true

### Additional context
see https://github.com/census-instrumentation/opencensus-node/blob/e40d5ccb2cfa63e047b532f8fd45c8dbda998001/packages/opencensus-core/src/trace/model/tracer-base.ts#L265-L267

problem is that `options.spanContext.options` is 0 and the condition is never true then. you would rather want to check if its set or a number

on a side-note, https://github.com/census-instrumentation/opencensus-node/blob/e40d5ccb2cfa63e047b532f8fd45c8dbda998001/packages/opencensus-propagation-jaeger/src/jaeger-format.ts#L89-L95 suffers the same problem but fortunately its safe as the flags are initialized with `0`. 

### Workaround
before doing starting rootSpan
>tracing.tracer.startRootSpan(traceOptions, (rootSpan) => {

do sth like
```js
      // setup trace context propagation
      const propagation = new JaegerFormat();
      const headers = req.headers;
      const path = req.url ? url.parse(req.url).pathname || '' : '';
      const getter = {
        getHeader(name) {
          return headers[name];
        },
      };

      const traceOptions = {
        name: path,
        kind: SpanKind.SERVER
      };

      const spanContext = propagation.extract(getter);
      if (spanContext) {
        traceOptions.spanContext = spanContext;

        // fix the bug where do-not-sample flag is ignored by CoreTracerBase
        const sampled = spanContext.options & SAMPLED_VALUE;
        if (!sampled) traceOptions.samplingRate = 0;
      }
```

because samplingRate has precedence over propagated trace options

**Comment by mayurkale22** [comment]
Thanks for reporting this!

If you are feeling motivated, maybe you can attempt to write solution and open a PR.
