### ISSUE TITLE
Please update the google-auth-library >=6.1.0 and googleapis >=60.0.1

### ISSUE THREAD

**Issue by saugatadutta** [census-instrumentation/opencensus-node#857]
Please answer these questions before submitting a bug report.

### What version of OpenCensus are you using?
0.0.22

### What version of Node are you using?
v12.18.1

### What did you do?
If possible, provide a recipe for reproducing the error.
Prototype Pollution in node-forge

Path:  @opencensus/exporter-stackdriver > googleapis > google-auth-library > gtoken > google-p12-pem > node-forge  
Path:  @opencensus/exporter-stackdriver > google-auth-library > gtoken > google-p12-pem > node-forge

More info: https://npmjs.com/advisories/1561

**Comment by aabmass** [comment]
This was fixed in #887
