### ISSUE TITLE
jaeger: process details are not being set.

### ISSUE THREAD

**Issue by tcolgate** [census-instrumentation/opencensus-node#86]
`process.hostname` and `process.ip` are not being set in the final spans. I suspect this is true for any other tags passed in to the constructor.

**Comment by kjin** [comment]
@tcolgate Are the Jaeger modules ready for another release, or did you have more changes that you were planning to get in first?

**Comment by tcolgate** [comment]
@kjin a release would be great, along with the propagator. It would be even better if we could get #78 in, but that would require a release of core. Also, the fixes for the http integrations would be useful. Things are looking really quite usable now and I'm kind of itching to get us using this in a few projects.
