### ISSUE TITLE
A Security Vulnerability with deep dependency `ansi-regex`

### ISSUE THREAD

**Issue by marzieh-kazemi** [census-instrumentation/opencensus-node#946]
Please answer these questions before submitting a bug report.

### What version of OpenCensus are you using?
0.1.0

### What version of Node are you using?
>=14

### What did you do?
npm audit fix does not fix it.

### What did you expect to see?
no security vulnerability issue
![Uploading Screenshot 2021-11-09 at 9.40.04 AM.png…]()

### What did you see instead?
found 4 moderate severity vulnerabilities in 976 scanned packages

**Comment by aabmass** [comment]
It looks like this is pulled in by lerna which is a dev dependency, so not a production vulnerability.

**Comment by aabmass** [comment]
Unfortunately, lerna can't be upgraded to 4.0.0 because it no longer supports node8. While OC libraries would continue to work, the CI pipeline would break.
